name: .NET

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime:
          - win-x64
          - win-x86
          - win-arm
          - win-arm64
          - linux-x64
          - linux-musl-x64
          - linux-arm
          - linux-arm64
          - osx-x64
      fail-fast: true


    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.8.x

    - name: Restore depends
      run: dotnet restore

    - name: Publish with ${{ matrix.runtime }}
      run: |
        dotnet publish -c Release \
          --runtime ${{ matrix.runtime }} \
          --output ./build \
          --self-contained true \
          -p:PublishSingleFile=true \
          -p:PublishTrimmed=true

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.runtime }}
        path: ./build/*
